<?php

declare(strict_types=1);

namespace OpenClaw\Services;

defined('ABSPATH') || exit;

/**
 * Tiered Image Service for automatic thumbnail generation.
 *
 * Fallback chain:
 *   1. AI Image Generation (Gemini Flash Image / DALL-E)
 *   2. Stock Photo (Pexels → Unsplash)
 *   3. None (post created without thumbnail)
 */
class ImageService {

    /**
     * Get a thumbnail for a blog post using the tiered fallback chain.
     *
     * @param string $content  The article content (used to build AI prompt).
     * @param string $title    The article title.
     * @param string $keyword  The SEO keyword.
     * @param int    $post_id  The WordPress post ID.
     * @return array{success: bool, source: string, attachment_id: int|null, message: string}
     */
    public function getThumbnail(string $content, string $title, string $keyword, int $post_id): array {
        $settings = \OpenClaw\Admin\Settings::get_decrypted_settings();

        // Tier 1: AI Image Generation.
        if (! empty($settings['image_gen_enabled'])) {
            $prompt  = $this->buildPrompt($content, $title, $keyword);
            $result  = $this->tryAiGeneration($prompt, $settings);

            if ($result !== null) {
                $upload = $this->uploadTempFile($result['data'], $result['mime'], $title, $post_id);
                if ($upload['success']) {
                    return [
                        'success'       => true,
                        'source'        => 'ai',
                        'attachment_id' => $upload['attachment_id'],
                        'message'       => sprintf('Thumbnail generated by AI (%s).', $settings['image_gen_provider'] ?? 'gemini'),
                    ];
                }
                // AI generated image but upload failed — log and continue to stock photo.
                // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
                error_log('[OpenClaw ImageService] AI image upload failed: ' . $upload['message']);
            }
        }

        // Tier 2: Stock Photo (Pexels → Unsplash).
        $search_term = ! empty($keyword) ? $keyword : $title;
        $stock_url   = $this->tryStockPhoto($search_term, $settings);

        if ($stock_url !== null) {
            $sideload = $this->sideloadImage($stock_url, $post_id, $title);
            if ($sideload['success']) {
                return [
                    'success'       => true,
                    'source'        => 'stock',
                    'attachment_id' => $sideload['attachment_id'],
                    'message'       => 'Thumbnail from stock photo.',
                ];
            }
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
            error_log('[OpenClaw ImageService] Stock photo upload failed: ' . $sideload['message']);
        }

        // Tier 3: No image available.
        return [
            'success'       => false,
            'source'        => 'none',
            'attachment_id' => null,
            'message'       => 'Could not generate or find a thumbnail image. Post created without thumbnail.',
        ];
    }

    /**
     * Build an AI image generation prompt from article content.
     */
    private function buildPrompt(string $content, string $title, string $keyword): string {
        // Summarize content — take first 500 chars of plain text.
        $plain = wp_strip_all_tags($content);
        $summary = mb_substr($plain, 0, 500);

        $prompt  = "Create a professional, high-quality blog featured image for an article.\n\n";
        $prompt .= "Article title: \"{$title}\"\n";

        if (! empty($keyword)) {
            $prompt .= "Main topic/keyword: \"{$keyword}\"\n";
        }

        $prompt .= "Article summary: \"{$summary}\"\n\n";
        $prompt .= "Requirements:\n";
        $prompt .= "- Professional photography or illustration style\n";
        $prompt .= "- Visually appealing, suitable for a blog header\n";
        $prompt .= "- 16:9 landscape aspect ratio\n";
        $prompt .= "- No text on the image\n";
        $prompt .= "- Clean, modern design with good color composition";

        return $prompt;
    }

    /**
     * Try AI image generation.
     *
     * @return array{data: string, mime: string}|null Raw image data or null on failure.
     */
    private function tryAiGeneration(string $prompt, array $settings): ?array {
        $provider = $settings['image_gen_provider'] ?? 'gemini';

        switch ($provider) {
            case 'gemini':
                return $this->generateWithGemini($prompt, $settings);
            case 'openai_dalle':
                return $this->generateWithDalle($prompt, $settings);
            default:
                return null;
        }
    }

    /**
     * Generate image using Gemini Flash Image model.
     *
     * Uses the same Gemini API key from LLM settings.
     *
     * @return array{data: string, mime: string}|null
     */
    private function generateWithGemini(string $prompt, array $settings): ?array {
        $api_key = $settings['image_gemini_api_key'] ?? $settings['gemini_api_key'] ?? '';
        if (empty($api_key)) {
            return null;
        }

        $model = 'gemini-2.5-flash-image';
        $url   = 'https://generativelanguage.googleapis.com/v1beta/models/' . $model . ':generateContent';

        $body = [
            'contents' => [
                [
                    'parts' => [
                        ['text' => $prompt],
                    ],
                ],
            ],
            'generationConfig' => [
                'responseModalities' => ['TEXT', 'IMAGE'],
                'responseMimeType'   => 'text/plain',
            ],
        ];

        $response = wp_remote_post($url, [
            'timeout' => 60,
            'headers' => [
                'Content-Type'   => 'application/json',
                'x-goog-api-key' => $api_key,
            ],
            'body' => wp_json_encode($body),
        ]);

        if (is_wp_error($response)) {
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
            error_log('[OpenClaw ImageService] Gemini API error: ' . $response->get_error_message());
            return null;
        }

        $status = wp_remote_retrieve_response_code($response);
        $data   = json_decode(wp_remote_retrieve_body($response), true);

        if ($status !== 200) {
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
            error_log('[OpenClaw ImageService] Gemini image gen failed (HTTP ' . $status . '): ' . wp_json_encode($data['error'] ?? []));
            return null;
        }

        // Find inline image data in response parts.
        $parts = $data['candidates'][0]['content']['parts'] ?? [];
        foreach ($parts as $part) {
            if (isset($part['inlineData'])) {
                return [
                    'data' => base64_decode($part['inlineData']['data']),
                    'mime' => $part['inlineData']['mimeType'] ?? 'image/png',
                ];
            }
        }

        return null;
    }

    /**
     * Generate image using OpenAI DALL-E.
     *
     * Uses the OpenAI API key from LLM settings.
     *
     * @return array{data: string, mime: string}|null
     */
    private function generateWithDalle(string $prompt, array $settings): ?array {
        $api_key = $settings['openai_api_key'] ?? '';
        if (empty($api_key)) {
            return null;
        }

        $model = $settings['dalle_model'] ?? 'dall-e-3';
        $url   = 'https://api.openai.com/v1/images/generations';

        $body = [
            'model'           => $model,
            'prompt'          => mb_substr($prompt, 0, 4000),
            'n'               => 1,
            'size'            => '1792x1024', // 16:9-ish for DALL-E 3
            'response_format' => 'b64_json',
        ];

        $response = wp_remote_post($url, [
            'timeout' => 60,
            'headers' => [
                'Content-Type'  => 'application/json',
                'Authorization' => 'Bearer ' . $api_key,
            ],
            'body' => wp_json_encode($body),
        ]);

        if (is_wp_error($response)) {
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
            error_log('[OpenClaw ImageService] DALL-E API error: ' . $response->get_error_message());
            return null;
        }

        $status = wp_remote_retrieve_response_code($response);
        $data   = json_decode(wp_remote_retrieve_body($response), true);

        if ($status !== 200) {
            // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
            error_log('[OpenClaw ImageService] DALL-E failed (HTTP ' . $status . '): ' . wp_json_encode($data['error'] ?? []));
            return null;
        }

        $b64 = $data['data'][0]['b64_json'] ?? '';
        if (empty($b64)) {
            return null;
        }

        return [
            'data' => base64_decode($b64),
            'mime' => 'image/png',
        ];
    }

    /**
     * Try stock photo providers: Pexels → Unsplash.
     *
     * @return string|null Image URL or null.
     */
    private function tryStockPhoto(string $search_term, array $settings): ?string {
        // Try Pexels first.
        $pexels_key = $settings['pexels_api_key'] ?? '';
        if (! empty($pexels_key)) {
            $url = $this->searchPexels($search_term, $pexels_key);
            if ($url !== null) {
                return $url;
            }
        }

        // Fallback to Unsplash.
        $unsplash_key = $settings['unsplash_api_key'] ?? '';
        if (! empty($unsplash_key)) {
            $url = $this->searchUnsplash($search_term, $unsplash_key);
            if ($url !== null) {
                return $url;
            }
        }

        return null;
    }

    /**
     * Search Pexels for a landscape photo.
     *
     * @return string|null Direct image URL.
     */
    private function searchPexels(string $query, string $api_key): ?string {
        $url = add_query_arg([
            'query'       => $query,
            'per_page'    => 5,
            'orientation' => 'landscape',
        ], 'https://api.pexels.com/v1/search');

        $response = wp_remote_get($url, [
            'timeout' => 15,
            'headers' => [
                'Authorization' => $api_key,
            ],
        ]);

        if (is_wp_error($response)) {
            return null;
        }

        $data = json_decode(wp_remote_retrieve_body($response), true);
        $photos = $data['photos'] ?? [];

        if (empty($photos)) {
            return null;
        }

        // Pick a random photo from results for variety.
        $photo = $photos[array_rand($photos)];
        return $photo['src']['large2x'] ?? $photo['src']['large'] ?? $photo['src']['original'] ?? null;
    }

    /**
     * Search Unsplash for a landscape photo.
     *
     * @return string|null Direct image URL.
     */
    private function searchUnsplash(string $query, string $api_key): ?string {
        $url = add_query_arg([
            'query'       => $query,
            'per_page'    => 5,
            'orientation' => 'landscape',
        ], 'https://api.unsplash.com/search/photos');

        $response = wp_remote_get($url, [
            'timeout' => 15,
            'headers' => [
                'Authorization' => 'Client-ID ' . $api_key,
            ],
        ]);

        if (is_wp_error($response)) {
            return null;
        }

        $data    = json_decode(wp_remote_retrieve_body($response), true);
        $results = $data['results'] ?? [];

        if (empty($results)) {
            return null;
        }

        // Pick a random result for variety.
        $photo = $results[array_rand($results)];
        return $photo['urls']['regular'] ?? $photo['urls']['full'] ?? null;
    }

    /**
     * Upload raw image data (from AI generation) to WordPress Media Library.
     *
     * @param string $image_data Raw binary image data.
     * @param string $mime_type  MIME type (e.g., image/png).
     * @param string $title      Used for filename.
     * @param int    $post_id    Parent post ID.
     * @return array{success: bool, attachment_id?: int, message?: string}
     */
    private function uploadTempFile(string $image_data, string $mime_type, string $title, int $post_id): array {
        if (empty($image_data)) {
            return ['success' => false, 'message' => 'Empty image data.'];
        }

        // Determine extension from MIME.
        $ext_map = [
            'image/png'  => 'png',
            'image/jpeg' => 'jpg',
            'image/webp' => 'webp',
        ];
        $ext = $ext_map[$mime_type] ?? 'png';

        // Create a safe filename from the title.
        $filename = sanitize_file_name(sanitize_title($title)) . '-ai-generated.' . $ext;

        // Use wp_upload_bits to save the file.
        $upload = wp_upload_bits($filename, null, $image_data);

        if (! empty($upload['error'])) {
            return ['success' => false, 'message' => $upload['error']];
        }

        // Create attachment.
        if (! function_exists('wp_generate_attachment_metadata')) {
            require_once ABSPATH . 'wp-admin/includes/image.php';
        }

        $attachment = [
            'post_mime_type' => $mime_type,
            'post_title'     => sanitize_text_field($title) . ' (AI Generated)',
            'post_content'   => '',
            'post_status'    => 'inherit',
        ];

        $attachment_id = wp_insert_attachment($attachment, $upload['file'], $post_id);

        if (is_wp_error($attachment_id)) {
            return ['success' => false, 'message' => $attachment_id->get_error_message()];
        }

        $metadata = wp_generate_attachment_metadata($attachment_id, $upload['file']);
        wp_update_attachment_metadata($attachment_id, $metadata);

        set_post_thumbnail($post_id, $attachment_id);

        return [
            'success'       => true,
            'attachment_id' => $attachment_id,
        ];
    }

    /**
     * Sideload an image from URL into WordPress Media Library.
     *
     * @param string $url     Remote image URL.
     * @param int    $post_id Parent post ID.
     * @param string $title   Description/alt text.
     * @return array{success: bool, attachment_id?: int, message?: string}
     */
    private function sideloadImage(string $url, int $post_id, string $title): array {
        if (! function_exists('media_sideload_image')) {
            require_once ABSPATH . 'wp-admin/includes/image.php';
            require_once ABSPATH . 'wp-admin/includes/file.php';
            require_once ABSPATH . 'wp-admin/includes/media.php';
        }

        $attachment_id = media_sideload_image($url, $post_id, $title, 'id');

        if (is_wp_error($attachment_id)) {
            return ['success' => false, 'message' => $attachment_id->get_error_message()];
        }

        set_post_thumbnail($post_id, $attachment_id);

        return [
            'success'       => true,
            'attachment_id' => $attachment_id,
        ];
    }
}
